### ISSUE TITLE
Unclear Installation Instructions

### ISSUE THREAD

**Issue by PewolfP** [LennyPhoenix/GodotDiscordSDK#19]
Hey, I've been having problems with setting things up for my Godot project. When using the example it works fine, but when I try to follow [these](https://github.com/LennyPhoenix/GodotDiscordSDK/wiki/Installation) instructions. I tried following them but they're too unclear for me. When I try to do everything I get `Attempt to call function 'new' in base 'NativeScript' on a null instance.`, so it doesn't find the library. What I did:

1. Downloaded the discord_sdk folder;
2. Tried to download the  Godot Discord SDK shared libraries, but couldn't figure out how (clicked the link), probably because of my bad knowledge of Github. So I follow the instructions from the "compile" link and try to run git but get an error - So I skip that step and run setup.bat;
3. Download the Discord Game SDK files, paste the lib folder into the project (maybe I was supposed to do something else?);
4. I try to compile it with Scons but that also fails;
5. I check the .gdnlib file, it looks good;
6. Code doesn't work. I get the error mentioned in the first part.

What did I do wrong? Thanks for any help (:

**Comment by LennyPhoenix** [comment]
My apologies, I forgot to link the releases page on the installation instructions!
Head [here](https://github.com/LennyPhoenix/GodotDiscordSDK/releases) to download the Godot Discord SDK shared libraries and follow the instructions from there.

For compilation, you should be copying the individual files of the Game SDK lib folder manually as they aren't structured how they should be by default (you may need to rename some files). I also can't help if you don't provide the error message, so that would be appreciated in future.

**Comment by LennyPhoenix** [comment]
The installation instructions should have the correct link now.

**Comment by PewolfP** [comment]
Wow, thanks for replying so quickly! The info is a lot clearer now, thanks!

**Comment by LennyPhoenix** [comment]
No problem!
